### ISSUE TITLE
(Admin) Use Story 2,3,4,5

### ISSUE THREAD

**Issue by dmilsap** [OwenAdams2023/Group12#10]
Create the diagrams for Admin User Story 2,3,4,5

**Comment by Arh3825** [comment]
Admin Swimlane 2,3,4,5
![Admin_Swimline_AD_Account drawio](https://github.com/OwenAdams2023/Group12/assets/129342936/b6ab4dba-d715-47da-935d-10bcdc878d22)
![Admin_Swimline_AD_Product drawio](https://github.com/OwenAdams2023/Group12/assets/129342936/15eb1157-398c-4bfb-b8c9-64207c2fa44c)
![Admin_Swimline_AD_Modification drawio](https://github.com/OwenAdams2023/Group12/assets/129342936/dafd1201-7238-41d5-a5a3-cb69b603f1fa)

![Admin_Swimline_Account_View drawio](https://github.com/OwenAdams2023/Group12/assets/129342936/8c943a10-b8d6-4312-82b0-ee52010fd726)
s2023/Group12/assets/129342936/9bac3ba5-fd8f-42d0-9148-d1b7ebb71706)

**Comment by Arh3825** [comment]
Admin State 2,3,4,5
![Admin_State_AD_Account drawio](https://github.com/OwenAdams2023/Group12/assets/129342936/73680c60-ca3d-4a82-90d1-7c0945f90efe)
![Admin_State_AD_Products drawio](https://github.com/OwenAdams2023/Group12/assets/129342936/99edd327-12f1-470b-acf8-7847c775218d)
![Admin_State_AD_Modifications drawio](https://github.com/OwenAdams2023/Group12/assets/129342936/c410b472-ee43-4c01-a07d-b8095d53e85a)
![Admin_State_View_Account drawio](https://github.com/OwenAdams2023/Group12/assets/129342936/5d9e1195-9439-40d7-a279-91c47da3d9b5)

**Comment by Arh3825** [comment]
Admin Sequence 2,3,4,5
![Admin_Sequence_AD_Account drawio](https://github.com/OwenAdams2023/Group12/assets/129342936/18087134-6764-465a-b006-1542830515f9)
![Admin_Sequence_AD_Product drawio](https://github.com/OwenAdams2023/Group12/assets/129342936/afc0df35-7c36-43e7-9883-3eec9325624c)
![Admin_Sequence_AD_Product_Mod drawio](https://github.com/OwenAdams2023/Group12/assets/129342936/5b83db03-278d-4b53-9de4-4459d31642f6)
![Admin_Sequence_View_Account drawio](https://github.com/OwenAdams2023/Group12/assets/129342936/ba273f8c-61e6-463e-b248-fbc7ec91b12d)

**Comment by Arh3825** [comment]
All diagrams submitted and added to the wiki
