### ISSUE TITLE
(Buyer) Use Story 3,4,5,6

### ISSUE THREAD

**Issue by dmilsap** [OwenAdams2023/Group12#12]
Create diagrams for buyer Use stories 3,4,5,6.

**Comment by nishaadh** [comment]
Find attached UML Diagrams for Buyer Story 3, 4, 5, 6

![UMLSequence-BuyerBuy](https://github.com/OwenAdams2023/Group12/assets/134630577/3f6f3443-7b60-4810-a5af-131f8181ef1b)
![UMLSequence-BuyerCompare](https://github.com/OwenAdams2023/Group12/assets/134630577/7b515032-785a-4ba5-947d-5687043bb07c)
![UMLSequence-BuyerReturn](https://github.com/OwenAdams2023/Group12/assets/134630577/b7d1e8c2-9ec2-4a9f-847b-458352e36238)
![UMLSequence-BuyerSearch](https://github.com/OwenAdams2023/Group12/assets/134630577/ab744841-f11d-4bc5-9da4-d24d046c33aa)

**Comment by nishaadh** [comment]
Find attached the Swimlane Diagram Buyer Use story 3, 4, 5, 6

![Swimlane-buy](https://github.com/OwenAdams2023/Group12/assets/134630577/6cacd611-fd2e-42b7-be79-245eeada981a)
![Swimlane-compare](https://github.com/OwenAdams2023/Group12/assets/134630577/c0270cec-1ade-4b02-b9fd-0fafeed4df94)
![Swimlane-return](https://github.com/OwenAdams2023/Group12/assets/134630577/53836aa7-4c8d-4b5b-80d8-87eb23f0d013)
![Swimlane-search](https://github.com/OwenAdams2023/Group12/assets/134630577/29d17f96-7d85-404f-bd8a-f82a175724b1)

**Comment by nishaadh** [comment]
Find attached State Diagrams Buyer Use Case 3, 4, 5, 6

![StateDiagram-Buy](https://github.com/OwenAdams2023/Group12/assets/134630577/3ba3fbb3-db69-4b7d-a9d3-264e2df5c89c)
![StateDiagram-Compare](https://github.com/OwenAdams2023/Group12/assets/134630577/a00cfd8e-90cc-4765-b35d-36416a9f88c9)
![StateDiagram-Return](https://github.com/OwenAdams2023/Group12/assets/134630577/9f74a5d1-581c-45b0-abbc-8522261c994f)
![StateDiagram-Search](https://github.com/OwenAdams2023/Group12/assets/134630577/61da91f4-44f8-4ceb-bf9c-4ad180c61a76)
