### ISSUE TITLE
Login/ Account Creation Use Stories

### ISSUE THREAD

**Issue by dmilsap** [OwenAdams2023/Group12#13]
Create diagrams for 
(Admin) Use Story 1
(Buyer) Use Story 1,2
(Seller) Use Story 1

**Comment by OwenAdams2023** [comment]
I will upload the sequence, state, and swimlane diagrams for Admin 1, Buyer 1 & 2, and Seller 1.

**Comment by OwenAdams2023** [comment]
Sequence diagrams for Admin Login, Buyer Login, Buyer Account Creation, and Seller Account Creation
<img width="466" alt="image" src="https://github.com/OwenAdams2023/Group12/assets/126014056/9583b30d-9c32-4d02-8374-2e3d4a16fbe0">
<img width="436" alt="image" src="https://github.com/OwenAdams2023/Group12/assets/126014056/ddfd0e8a-4f09-4d5d-931b-a8e44dc55602">
<img width="449" alt="image" src="https://github.com/OwenAdams2023/Group12/assets/126014056/99c20776-9704-4c74-859d-00fd8aaa0c3d">
<img width="426" alt="image" src="https://github.com/OwenAdams2023/Group12/assets/126014056/42fcdb3c-6846-4a53-b3e9-a977d573444c">

**Comment by OwenAdams2023** [comment]
State Diagrams for Admin Login, Buyer Login, Buyer Account Creation, and Seller Account Creation
<img width="458" alt="image" src="https://github.com/OwenAdams2023/Group12/assets/126014056/9fdadba1-e81f-4c75-91ab-59988e38890a">
<img width="439" alt="image" src="https://github.com/OwenAdams2023/Group12/assets/126014056/ee78d841-8906-477a-87f5-0ea942a9e71b">
<img width="443" alt="image" src="https://github.com/OwenAdams2023/Group12/assets/126014056/f50df091-0941-4e3f-98fd-035f83946f18">
<img width="434" alt="image" src="https://github.com/OwenAdams2023/Group12/assets/126014056/76fe4d33-ee10-4b5b-80f7-c31c611cc767">

**Comment by OwenAdams2023** [comment]
Swimlane diagrams for Admin Login, Buyer Login, Buyer Account Creation, and Seller Account Creation
<img width="445" alt="image" src="https://github.com/OwenAdams2023/Group12/assets/126014056/a8333ef3-bd5b-4b2f-ac1f-6342929a1cc1">
<img width="442" alt="image" src="https://github.com/OwenAdams2023/Group12/assets/126014056/b0aa328a-4852-4ba1-a8ee-30d42d08f515">
<img width="431" alt="image" src="https://github.com/OwenAdams2023/Group12/assets/126014056/ed6d87ed-7248-4dde-9081-09124a696fb7">
<img width="440" alt="image" src="https://github.com/OwenAdams2023/Group12/assets/126014056/bde93c69-f536-4355-b1d2-471a8efff4a7">
