### ISSUE TITLE
Component Level Design

### ISSUE THREAD

**Issue by dmilsap** [OwenAdams2023/Group12#15]
Create component level design diagrams

**Comment by dmilsap** [comment]
These are the current Component Level Design Diagrams. Waiting for review.
![componentLevel_data](https://github.com/OwenAdams2023/Group12/assets/156827373/deb1877a-5d6e-47a2-a0b3-5803c59ddd6b)
![componentLevel_middle](https://github.com/OwenAdams2023/Group12/assets/156827373/71fa75f1-8d34-4542-a5ca-5ab685bd5d3b)
![componentLevel_presentation](https://github.com/OwenAdams2023/Group12/assets/156827373/e5c6736d-b0eb-4930-b9d2-1a67be174445)

**Comment by Arh3825** [comment]
Looks good
