### ISSUE TITLE
Use Case Diagrams

### ISSUE THREAD

**Issue by dmilsap** [OwenAdams2023/Group12#16]
Create a admin, buyer, and seller use case diagram.

**Comment by nishaadh** [comment]
Find attached admin, buyer and seller use case diagram
![UseCase-Admin](https://github.com/OwenAdams2023/Group12/assets/134630577/7226fdc1-ef40-4457-b39e-da5572b66f67)
![UseCase-Buyer](https://github.com/OwenAdams2023/Group12/assets/134630577/2ebf5140-2165-406c-a778-7d1be6647c9e)
![UseCase-Seller](https://github.com/OwenAdams2023/Group12/assets/134630577/f27055eb-16a5-4ad9-9f3a-be2e23cf542e)
