### ISSUE TITLE
SRS Documetnn Section 4/5

### ISSUE THREAD

**Issue by Arh3825** [OwenAdams2023/Group12#5]
Hey Destiny, can you please complete section 4/5 of the SRS Document by Friday Feb 2nd before our meeting please?

Thank you!

**Comment by dmilsap** [comment]
[IEEE-Intro-to-SE_SRS_.docx](https://github.com/OwenAdams2023/Group12/files/14145881/IEEE-Intro-to-SE_SRS_.docx)

This my current changes to section 4/5. It needs to be reviewed by the group.  I will close this issue after the 2/2/2024 meeting.

**Comment by Arh3825** [comment]
Reviewed and Approved
