### ISSUE TITLE
Convert SRS Document

### ISSUE THREAD

**Issue by Arh3825** [OwenAdams2023/Group12#6]
Owen, can you please convert our Google Doc of the SRS document into a Word document to adjust formatting?
After that is done please convert it into a pdf for submission.

Thank You

**Comment by Arh3825** [comment]
Make sure you submit the PDF to Canvas and then add the finished PDF to Git hub :)

**Comment by OwenAdams2023** [comment]
Got SRS pdf submitted to canvas and did a pull request to merge SRS from sprint1 to main
