### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by Arh3825** [OwenAdams2023/Group12#8]
Please add all user stories to the Wiki for our first Sprint

**Comment by dmilsap** [comment]
Buyer use stories added to the wiki.

**Comment by Arh3825** [comment]
Admin Use Stories and Seller Use Stories added to the Wiki @nishaadh please review it when you close this issue

**Comment by nishaadh** [comment]
Everything looks good. I reviewed it and now I am closing this issue.
